"""
`styles` are generated by ChatGPT
"""

styles = [
    { "name": "Luxurious",      "description": "Emphasizes exclusivity, high-end quality, and sophistication."                              },
    { "name": "Energetic",      "description": "Full of vitality, excitement, and dynamic imagery."                                         },
    { "name": "Minimalistic",   "description": "Simple, clean, and focused on essential elements."                                          },
    { "name": "Playful",        "description": "Fun, whimsical, and light-hearted with vibrant colors and engaging designs."                },
    { "name": "Eco-friendly",   "description": "Highlights sustainability, nature, and environmentally conscious elements."                 },
    { "name": "Bold",           "description": "Striking, powerful visuals and strong messages."                                            },
    { "name": "Elegant",        "description": "Refined, graceful, and typically subtle in presentation."                                   },
    { "name": "Retro",          "description": "Uses nostalgic elements, often referencing past trends or styles."                          },
    { "name": "Futuristic",     "description": "Sleek, modern, and often tech-centric with advanced or high-tech imagery."                  },
    { "name": "Organic",        "description": "Soft, earthy tones and natural aesthetics, often appealing to health-conscious consumers."  },
    { "name": "Innovative",     "description": "Focuses on groundbreaking ideas and cutting-edge design."                                   },
    { "name": "Sporty",         "description": "Energetic, athletic, and focused on action or performance."                                 },
    { "name": "Friendly",       "description": "Warm, approachable, and often casual with human-centered design."                           },
    { "name": "Artistic",       "description": "Emphasizes creativity, unique aesthetics, and individual expression."                       },
    { "name": "Glamorous",      "description": "Glitzy, glamorous, and focused on beauty or the allure of the product."                     },
    { "name": "Urban",          "description": "Edgy, cool, and often linked with street culture or city life."                             },
    { "name": "Professional",   "description": "Clean, formal, and structured, often geared toward B2B audiences."                          },
    { "name": "Adventurous",    "description": "Rugged, bold, and aimed at thrill-seekers or outdoor enthusiasts."                          },
    { "name": "Nostalgic",      "description": "Evokes memories, traditions, and familiarity from the past."                                },
    { "name": "Quirky",         "description": "Offbeat, unique, and often unconventional in its presentation."                             },
]


STYLES = list()
STYLES_PROMPT = dict()

for s in styles:
    s_name = s['name'].lower()
    s_desc = s['description']

    STYLES.append(s_name)
    STYLES_PROMPT[s_name] = s_desc

